### ISSUE TITLE
遇到报错

### ISSUE THREAD

**Issue by xiexiao6** [killnice/yolov5-D435i#9]
运行python main_debug.py
出现Using cache found in C:\Users\13939/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2023-11-14 Python-3.8.18 torch-2.1.0+cpu CPU

Fusing layers...
YOLOv5l6 summary: 476 layers, 76726332 parameters, 0 gradients, 111.2 GFLOPs
Adding AutoShape...
Traceback (most recent call last):
  File "main_debug.py", line 45, in <module>
    pipeline.start(config)
RuntimeError: Couldn't resolve requests

**Comment by respectNzy** [comment]
你好，请问解决了吗

**Comment by killnice** [comment]
> 运行python main_debug.py 出现Using cache found in C:\Users\13939/.cache\torch\hub\ultralytics_yolov5_master YOLOv5 2023-11-14 Python-3.8.18 torch-2.1.0+cpu CPU
> 
> Fusing layers... YOLOv5l6 summary: 476 layers, 76726332 parameters, 0 gradients, 111.2 GFLOPs Adding AutoShape... Traceback (most recent call last): File "main_debug.py", line 45, in pipeline.start(config) RuntimeError: Couldn't resolve requests

pipline那里是负责读取realsense数据流的，看起来像是软件驱动问题，你看看直接运行realsense演示读取图像与深度图的python程序能否运行
